In [2]:
import pandas as pd
from os import chdir
chdir('../Project_6/')

##  Parse: Encode search as document vector 

## Mine: Select document vectors for all pages from database

In [3]:
from sklearn.externals import joblib
transformer = joblib.load('/Users/karibenson/dsi/dsi-workspace/Project_6_KB/vectorizer.pkl')
transformer

Pipeline(steps=[('tfidf', TfidfVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm=u'l2', preprocessor=None, smooth_idf=Tru...TruncatedSVD(algorithm='randomized', n_components=500, n_iter=10,
       random_state=42, tol=0.0))])

In [5]:
from lib.encoding_module import get_searchterm_vector, get_page_vector

In [62]:
search_vector = get_searchterm_vector(transformer,"best pets")

In [19]:
from lib.database_module import select_all_page_vectors
all_page_vectors = select_all_page_vectors(location='remote')

Connected to server joshuacook.me.


## Model: Find five most similar documents based on document vectors

In [20]:
from sklearn.neighbors import NearestNeighbors

In [21]:
# K nearest neighbors finds class based on the class of the nearest neighbors.  neighbors returns the coordinates (vectors) of the neighbors, not the class.

In [56]:
all_page_vectors_dict = {}
for cat_name, vector in all_page_vectors:
    all_page_vectors_dict[cat_name] = vector


In [58]:
apv_df = pd.DataFrame.from_dict(all_page_vectors_dict, orient='index')

In [59]:
apv_df.head()

0         1         2         3         4         5    \
17645570  0.039274  0.055023 -0.014005 -0.016520  0.022691 -0.018724   
37019651  0.101253  0.161288 -0.224323  0.112926 -0.060645  0.066798   
9109512   0.039232  0.039217  0.008973 -0.047728 -0.015612  0.017161   
45260809  0.186930 -0.060678 -0.004299  0.012090  0.001639 -0.007242   
6565890   0.067058  0.092235 -0.103929  0.040591 -0.002851  0.008336   

               6         7         8         9      ...          490  \
17645570  0.002756  0.005556 -0.005737 -0.009030    ...    -0.010056   
37019651  0.023622  0.008715 -0.017338  0.008191    ...    -0.001198   
9109512   0.000355 -0.002134 -0.002816 -0.015128    ...     0.031067   
45260809  0.005464 -0.005203  0.001449  0.013998    ...     0.019338   
6565890  -0.013674 -0.000052  0.021902 -0.000659    ...     0.006890   

               491       492       493       494       495       496  \
17645570 -0.014171 -0.013905  0.003224  0.005246  0.004800  0.032152   
37019651 -0.016804 -0.015773 -0.009290 -0.000526  0.004315 -0.003473   
9109512   0.011480 -0.021530 -0.004341  0.004190  0.044702  0.011483   
45260809 -0.001007  0.019923  0.030012  0.018544 -0.058307 -0.000886   
6565890   0.005918 -0.003518 -0.013995 -0.002671  0.020586  0.001678   

               497       498       499  
17645570  0.011491  0.022782  0.003275  
37019651  0.003300 -0.009625 -0.005633  
9109512  -0.013307 -0.031249 -0.063539  
45260809 -0.040026 -0.012019  0.010476  
6565890  -0.004499  0.003813 -0.016608  

[5 rows x 500 columns]

In [22]:
this_NN = NearestNeighbors()

In [60]:
this_NN.fit(apv_df)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=5, p=2, radius=1.0)

In [67]:
search_vector.values()[0][0]

array([  1.38811587e-02,   2.12773781e-02,   1.59221774e-02,
        -2.40259368e-02,  -2.91117594e-02,   9.50175326e-03,
         5.27072057e-03,  -6.68969497e-03,   1.04174888e-02,
         6.28258459e-02,   2.58516624e-03,   2.63435818e-03,
         1.52540655e-03,  -1.03566805e-03,  -3.22923118e-03,
        -4.09538510e-04,  -2.28082427e-03,  -3.54780695e-03,
        -1.04429021e-03,   7.60847922e-04,  -1.66015944e-03,
         2.32984601e-03,   2.87155664e-03,   1.16763610e-03,
         6.66826554e-04,   3.80653476e-03,   4.53914731e-03,
        -8.73076224e-03,  -1.09129363e-02,   1.41013758e-03,
        -4.11768712e-03,  -1.17814224e-02,  -5.31667437e-03,
        -3.76368070e-03,  -2.08001119e-03,   2.61641949e-03,
         1.74157627e-03,   7.53883728e-03,  -3.71687333e-03,
        -8.51857519e-03,  -1.37850864e-02,  -1.69316696e-02,
         7.32884066e-03,  -5.50847094e-03,   3.37112603e-03,
        -8.34551388e-03,  -1.03670215e-02,  -9.64168798e-03,
        -9.37497310e-03,

In [68]:
this_NN.kneighbors(search_vector.values()[0][0])

/Users/karibenson/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


(array([[ 0.40158972,  0.41308359,  0.46097247,  0.46941345,  0.48540245]]),
 array([[1693, 1789,  712,  373, 1165]]))

In [71]:
apv_df.index[1693],apv_df.index[1789],apv_df.index[712],apv_df.index[373],apv_df.index[1165]

(8181732, 16654048, 13846997, 18007329, 2904185)

## Mine: Retrieve text for the five most similar documents

In [77]:
import lib.database_module as db

In [85]:
db.select_pages([8181732, 16654048, 13846997, 18007329, 2904185], location='remote')

Connected to server joshuacook.me.


[(2904185,
  'Simit (Turkish: simit, Arabic: \xd8\xb3\xd9\x85\xd9\x8a\xd8\xb7\xe2\x80\x8e, translit. sam\xc4\xabt\xcb\xa4\xe2\x80\x8e, Persian: \xd8\xb3\xdb\x8c\xd9\x85\xdb\x8c\xd8\xaa\xe2\x80\x8e, translit',
  'Simit (Turkish: simit, Arabic: \xd8\xb3\xd9\x85\xd9\x8a\xd8\xb7\xe2\x80\x8e, translit. sam\xc4\xabt\xcb\xa4\xe2\x80\x8e, Persian: \xd8\xb3\xdb\x8c\xd9\x85\xdb\x8c\xd8\xaa\xe2\x80\x8e, translit. s\xc4\xabm\xc4\xabt\xcb\xa4\xe2\x80\x8e, Bulgarian: \xd1\x81\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x82  simit ), gevrek (Turkish: gevrek, Bulgarian: \xd0\xb3\xd0\xb5\xd0\xb2\xd1\x80\xd0\xb5\xd0\xba, Macedonian: \xd1\x93\xd0\xb5\xd0\xb2\xd1\x80\xd0\xb5\xd0\xba, Serbian: \xd1\x92\xd0\xb5\xd0\xb2\xd1\x80\xd0\xb5\xd0\xba), bokegh (Armenian: \xd5\xa2\xd5\xb8\xd5\xaf\xd5\xa5\xd5\xb2), or koulouri (Greek: \xce\xba\xce\xbf\xcf\x85\xce\xbb\xce\xbf\xcf\x8d\xcf\x81\xce\xb9) is a circular bread, typically encrusted with sesame seeds or, less commonly, poppy, flax or sunflower seeds, found across the cuisines 